[package]
name = "arraydiff"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
build = "build.rs"

[lib]
name = "arraydiff"
path = "src/lib.rs"

[build-dependencies]
gcc = "*"
walkdir = "*"

[dependencies]
arithmetic = { path = "../libarithmetic" }
densearray = "*"
libc = "*"
operator = { path = "../liboperator" }
